#+#+title: Endplate - A Simple EDN Based Template System

* Introduction

~Endplate~ is an extremely simple templating system. In many of my projects,
especially web based projects, I often wanted a simple way to create templates that could
be used to manage structured data that is re-used in different contexts with only minor
changes. I also wanted something which builds on existing ~Clojure~ and ~Clojurescript~
functionality and works with native ~Clojure~ data types.

The obvious candidate was to do something based around EDN. As ~Clojure~ supports parsing of
EDN files and given how easy it is to add new types, using EDN seems like a simple and
flexible solution. Essentially, ~endplate~ uses an EDN format together with a custom
EDN dispatcher to add /tokens/ which can be dynamically replaced by EDN elements during parsing
of the template or include other /nested/ EDN files.

While ~endplate~ can be used to work with general EDN formatted data, it is particularly
useful for managing templates of ~hiccup~ data used for HTML generation. The =parse-template=
function includes an option to treat vectors as hiccup code. This means that any dynamicd
tag which expands to a vector will be treated as a hiccup vector is the first element is a
keyword and a string otherwise.

~Endplate~ can also be used for string templates. The =parse-template= function includes an
option that will enable all templates to be returned as a string, allowing for the
crweation of templates to aid in processing of text. 

Finally, ~Endplate~ supports the use of evaluated code in template parsing. Any template tag
whicvh expands into a list will be evaluated as a clojure form and wshatever value it
returns will be used as the value for the tag replacement. This functionality can be
disabled via an optional argument to =parse-template=.

* Install

* Usage

** Template Definition

A template can be any valid EDN element. Obviously, some elements are not terribly useful
as the basis for a template i.e. integer. Howsever, a template could be as simple as
that. More often, a template will be either a map or a vector.

In general, the root element type of the template will be what is returned when a template
is parsed, unless the optional argument ~:string?~ is true, in which case the =str= function
will be applied to the parsed template and its result returned as the function result
rather than the original template element.

A template definition can include the ~tag~  =#ep/val= followed by either a keyword or a
vector consisting of a keyword and value. The keyword will be looked up in the emplate
context map and if found, replaced by the associated value from the map. If not found and
the value associated with the tag is a vector, it will be replaced with the second value
in the vector. If the value associated with the tag is just the keyword and it is not
found in the context map, the vvalue /MISSING_TEMPLATE_VALUE-xxx/ is used to replacve the
tag.

Templates can also include the ~tag~ =#ep/incl=, which is used to include another template
within this template. The argument used with the tag is either a /string/, which specifies
the name of a template to include, or a /vector/, which has two elements. The first element
is a string which specifies the template to include and the second argument is a context
map used to lookup any =#ep/val= tags in the included template. 

See the =resources/templates= directory and the =endplate_tests.clj= file for examples of
templates and their results when parsed.

*** Simple Example

The following is a very simple template example which includes one template variable. The
template is in the file ~sample.edn~. 

#+begin_src clojure
   ["The value of foo is" #ep/val :foo]
#+end_src

If this template is parsed with the following call

#+begin_src clojure
  (parse-template "sample.edn" :context {:foo "my foo var value"})
  ;; => ["The value of foo is" "my foo var value"]

  ;; if we add the :string? optional argument, we get
  (parse-template "sample.edn" :context {:foo "my foo var value"} :string? true)
  ;; => "The value of foo is my foo var value"

  ;; If the keyword does not exist in the context you get a default fallback value of
  ;; "MISSING_TEMPLATE_VALUE_<keyword>"
  (parse-template "sample.edn" :context{})
  ;; => ["The value of foo is" "MISSING_TEMPLATE_VALUE_:foo"]
#+end_src

The second form of the var dispatcher allows for setting a default value inside the
template. For example, the template could be re-written as

#+begin_src clojure
  ["The value of foo is" #ep/var [:foo "default value"]]
#+end_src

With the above definition, when we re-run the above call to =parse-template= with a context
which does not include ~:foo~, we get;

#+begin_src clojure
  (parse-template "sample.edn" :context {})
  ;; => ["The value of foo is" "default value"]
#+end_src
