#+#+title: Endplate - A Simple EDN Based Template System

* Introduction

~Endplate~ is an extremely simple templating system. In many of my projects,
especially web based projects, I often wanted a simple way to create templates that could
be used to manage structured data that is re-used in different contexts with only minor
changes. I also wanted something which builds on existing ~Clojure~ and ~Clojurescript~
functionality and works with native ~Clojure~ data types.

The obvious candidate was to do something based around EDN. As ~Clojure~ supports parsing of
EDN files and given how easy it is to add new types, using EDN seems like a simple and
flexible solution. Essentially, ~endplate~ uses an EDN format together with a custom
EDN dispatcher to /tokens/ which can be dynamically replaced by EDN elements during parsing
of the template.

While ~endplate~ can be used to work with general EDN formatted data, it is particularly
useful for managing templates of ~hiccup~ data used for HTML generation. The =parse-template=
function includes an option to treat vectors as hiccup code. This means that any dynamicd
tag which expands to a vector will be treated as a hiccup vector is the first element is a
keyword and a string otherwise.

~Endplate~ can also be used for string templates. The =parse-template= function includes an
option that will enable all templates to be returned as a string, allowing for the
crweation of templates to aid in processing of text. 

Finally, ~Endplate~ supports the use of evaluated code in template parsing. Any template tag
whicvh expands into a list will be evaluated as a clojure form and wshatever value it
returns will be used as the value for the tag replacement. This functionality can be
disabled via an optional argument to =parse-template=.

* Install

* Usage

** Template Definition

A template can be any valid EDN element. Obviously, some elements are not terribly useful
as the basis for a template i.e. integer. Howsever, a template could be as simple as
that. More often, a template will be either a map or a vector.

In general, the root element type of the template will be what is returned when a template
is parsed, unless the optional argument ~:as-string~ is true, in which case the =str= function
will be applied to the parsed template and its result returned as the function result
rather than the original template element.

A template definition can include ~tags~ which will be replaced by the current value
associated with that tag in teh ~context~ element passed in as an argument to
=parse-template=. These dynamic tags are identified by the EDN dispatcher ~#endplate/var~. The
tag following the dispatcher is either a keyword or a vector. If it is a keyword, the
value is used as a key to get the associated value from the context map. This value is
then used as the replacement value for the dispatcher.

If the vfalue following the dispatcher is a vector, it is expected to be a vector of two
elements. The first element is a keyword and will be used to lookup the value in the
context map. If the keyword does not exist in the context map, the second element of the
vector is used as the default value.

*** Simple Example

The following is a very simple template example which includes one template variable. The
template is in the file ~sample.edn~. 

#+begin_src clojure
   ["The value of foo is" #endplate/val :foo]
#+end_src

If this template is parsed with the following call

#+begin_src clojure
  (parse-template "sample.edn" :context {:foo "my foo var value"})
  ;; => ["The value of foo is" "my foo var value"]

  ;; if we add the :as-string optional argument, we get
  (parse-template "sample.edn" :context {:foo "my foo var value"} :as-string true)
  ;; => "The value of foo is my foo var value"

  ;; If the keyword does not exist in the context you get a default fallback value of
  ;; "MISSING_TEMPLATE_VALUE_<keyword>"
  (parse-template "sample.edn" :context{})
  ;; => ["The value of foo is" "MISSING_TEMPLATE_VALUE_:foo"]
#+end_src

The second form of the var dispatcher allows for setting a default value inside the
template. For example, the template could be re-written as

#+begin_src clojure
  ["The value of foo is" #endplate/var [:foo "default value"]]
#+end_src

With the above definition, when we re-run the above call to =parse-template= with a context
which does not include ~:foo~, we get;

#+begin_src clojure
  (parse-template "sample.edn" :context {})
  ;; => ["The value of foo is" "default value"]
#+end_src
